backend = "glx";
vsync = true;

# Sombras (Desactivadas para no tapar bordes de bspwm)
shadow = false;

# Opacidad
active-opacity = 1.0;
inactive-opacity = 0.9;
frame-opacity = 1.0;

# Esquinas (Opcional, 0 para Red Team serio)
corner-radius = 0;

# Blur para Kitty
blur-method = "dual_kawase";
blur-strength = 5;
blur-background-exclude = [
    "window_type = 'desktop'"
];
