font_family JetBrainsMono NF
font_size 10.5

cursor_shape block
cursor_stop_blinking_after 0
scrollback_lines 2000
copy_on_select yes
mouse_hide_wait 0
select_by_word_characters @-./_~?&=%+#a
enable_audio_bell no
bell_on_tab "🔔 "
remember_window_size  no
window_border_width 1pt
draw_minimal_borders yes
window_padding_width 10
inactive_text_alpha 0.6
hide_window_decorations yes
confirm_os_window_close 0
tab_bar_style powerline


# BEGIN_KITTY_THEME
# H4ck3r
# END_KITTY_THEME# The basic colors
foreground              #78a378
background              #0c1018
selection_foreground    #0c1018
selection_background    #6DDE00

# Cursor colors
cursor                  #6DDE00
cursor_text_color       #0c1018

# URL underline color when hovering with mouse
url_color               #00fa5c

# Kitty window border colors
active_border_color     #9cf542
inactive_border_color   #578a29
bell_border_color       #76EA00

# Tab bar colors
active_tab_foreground   #0c1018
active_tab_background   #9cf542
inactive_tab_foreground #0c1018
inactive_tab_background #578a29
tab_bar_background      #0c1018

# The 16 terminal colors

# black
color0 #4A9801
color8 #4a4a4a

# red
color1 #6DDE00
color9 #0800ff

# green
color2  #00fa5c
color10 #4145b0

# yellow
color3  #76EA00
color11 #025dd4

# blue
color4  #578a29
color12 #7eb3f7

# magenta
color5  #9cf542
color13 #220991

# cyan
color6  #539e06
color14 #3a11f0

# white
color7  #00ff59
color15 #3b5eed
